defmodule ScopeResearchAndDevelopment.Repo.Migrations.LibraryDataLayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:libraries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:books) do
      modify :library_id,
             references(:libraries,
               column: :id,
               name: "books_library_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:books, [:library_id])
  end

  def down do
    drop_if_exists index(:books, [:library_id])

    drop constraint(:books, "books_library_id_fkey")

    alter table(:books) do
      modify :library_id, :uuid
    end

    drop table(:libraries)
  end
end
