defmodule ScopeResearchAndDevelopment.Repo.Migrations.AddLibraryResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      add :library_id, :uuid
    end
  end

  def down do
    alter table(:books) do
      remove :library_id
    end
  end
end
